### ISSUE TITLE
希望可以将name，artist 属性适配api接口，而不是将api直接作为字符串

### ISSUE THREAD

**Issue by shezhao** [Aziteee/halo-plugin-aplayer#3]
- 操作：嵌入代码或直接输入
![image](https://github.com/user-attachments/assets/dc2b8156-8733-4618-b3e7-2671b7bcd214)
![image](https://github.com/user-attachments/assets/9425a83a-3680-45b9-be6e-efe48a82ef27)

- 目前的效果
![image](https://github.com/user-attachments/assets/f6169536-7565-4175-8b37-0f1729d95abc)
- 希望的效果
     - name.artist属性可以检测是否为api接口，如果是则使用请求得到的name，与artist值。
- 感谢

**Comment by Aziteee** [comment]
也许你应该用meting。你可以在配置项里自定义meting的接口

**Comment by shezhao** [comment]
> 也许你应该用meting。你可以在配置项里自定义meting的接口

好的，或许我应该研究一下meting，感谢回复。
